---
title: "Safinaz Öksüz"
---

(/assets/images/safnazoksuz.jpg){fig-align="center"}

# Eğitim

-   Lisans, Biyomühendislik, Marmara Üniversitesi, Türkiye, 2014 - 2020.
-   Yüksek Lisans, Mühendislik Yönetimi, Hacettepe Üniversitesi, Türkiye, 2024- devam ediyor.

# İş Deneyimi

## İşler

1.  Firma adesso Turkey, pozisyon Ar-Ge Uzmanı, yıl 2024

2.  Firma Papilon Savunma, pozisyon Ar-Ge Uzmanı, yıl 2021 -2023

3.  Firma Marmara Üniversitesi Teknopark, pozisyon Proje Uzmanı, yıl 2021-2021

## Stajlar

1.  Firma BioMarin Pharmaceutical, pozisyon Stajyer, yıl 2019

2.  Firma Ioannina Üniversitesi Biyoteknoloji Araştırma Merkezi , pozisyon Stajyer, yıl 2017

# Projeler

1.  TÜBİTAK 1001..........................

# Yayınlar

1.  Dasdemir, E., Batta, R., Koksalan, M., Tezcaner Öztürk, D. (2022) “İHA Yönlendirmesi için Keşif Misyonu: Zaman Bağımlı Ödülleri ve Çoklu Bağlantıları Olan Çok Amaçlı Oryantiring Problemi”, Computers & Operations Research, 145: 105882

# Yetkinlikler

R, Quarto, Git, Python, Jira , MSProject

# Hobiler
